### ISSUE TITLE
$zippath="/tmp/ssl";

### ISSUE THREAD

**Issue by tncyrdmc** [avirus/sslmanager#1]
$zippath="/tmp/ssl";

web page error :  ERROR: temp directory not exist /tmp/ssl

but but there is /tmp/ssl folder

**Comment by avirus** [comment]
you're probably use some virtual filesystem in your php-apache installation.
try to insert "mkdir($zippath)" after quoted line

**Comment by avirus** [comment]
looks like problem is solved
